
sudo: required

language: generic

script:
  - sudo add-apt-repository -y ppa:acooks/libwebsockets6
  - sudo apt-get update -qq
  - sudo apt-get install libuv1-dev
  # This is needed by the libffi build in some cases. We will be able to remove
  # this once we change the native binding not to use libffi anymore.
  - sudo apt-get install texinfo

  - npm install -g esy

  - esy install
  - esy build
  - esy jbuilder exec ./main.exe

notifications:
  email:
    recipients:
      - antonbachin@yahoo.com
    on_success: always
    on_failure: always
